# data preprocessing h5 to csv

In [1]:
import h5py
import numpy as np
import pandas as pd

In [23]:
path = r'data\data.h5'
path_to = r'data\result_data_train.csv'

In [44]:
h5_store = pd.HDFStore(path)
a = h5_store.keys()
for key in a:
    print(h5_store.get(key))
with h5py.File(path, 'r') as f:
    print(f["Training_pixel"][()])
    print("=====")
    print(f["Training_label"][()])
    train_pixel = f["Training_pixel"][()]
    train_label = f["Training_label"][()]
    train_label = np.transpose(train_label)
    print(train_label.shape)
result_train = np.c_[train_pixel, train_label]
print(result_train)
train_pixel.shape[1]

[[ 70  80  82 ... 106 109  82]
 [151 150 147 ... 193 183 184]
 [231 212 156 ...  88 110 152]
 ...
 [ 74  81  87 ... 188 187 187]
 [222 227 203 ... 136 136 134]
 [195 199 205 ...   6  15  38]]
=====
[0 0 2 ... 4 0 4]
(28709,)
[[ 70  80  82 ... 109  82   0]
 [151 150 147 ... 183 184   0]
 [231 212 156 ... 110 152   2]
 ...
 [ 74  81  87 ... 187 187   4]
 [222 227 203 ... 136 134   0]
 [195 199 205 ...  15  38   4]]


2304

In [48]:
list_name_col = []
for i in range(train_pixel.shape[1]):
    list_name_col.append('pixel_' + str(i))
list_name_col.append('label_emo')
print(list_name_col)
df = pd.DataFrame(result_train, columns=list_name_col)
df.to_csv(path_to, sep=',', index_label='serial')

['pixel_0', 'pixel_1', 'pixel_2', 'pixel_3', 'pixel_4', 'pixel_5', 'pixel_6', 'pixel_7', 'pixel_8', 'pixel_9', 'pixel_10', 'pixel_11', 'pixel_12', 'pixel_13', 'pixel_14', 'pixel_15', 'pixel_16', 'pixel_17', 'pixel_18', 'pixel_19', 'pixel_20', 'pixel_21', 'pixel_22', 'pixel_23', 'pixel_24', 'pixel_25', 'pixel_26', 'pixel_27', 'pixel_28', 'pixel_29', 'pixel_30', 'pixel_31', 'pixel_32', 'pixel_33', 'pixel_34', 'pixel_35', 'pixel_36', 'pixel_37', 'pixel_38', 'pixel_39', 'pixel_40', 'pixel_41', 'pixel_42', 'pixel_43', 'pixel_44', 'pixel_45', 'pixel_46', 'pixel_47', 'pixel_48', 'pixel_49', 'pixel_50', 'pixel_51', 'pixel_52', 'pixel_53', 'pixel_54', 'pixel_55', 'pixel_56', 'pixel_57', 'pixel_58', 'pixel_59', 'pixel_60', 'pixel_61', 'pixel_62', 'pixel_63', 'pixel_64', 'pixel_65', 'pixel_66', 'pixel_67', 'pixel_68', 'pixel_69', 'pixel_70', 'pixel_71', 'pixel_72', 'pixel_73', 'pixel_74', 'pixel_75', 'pixel_76', 'pixel_77', 'pixel_78', 'pixel_79', 'pixel_80', 'pixel_81', 'pixel_82', 'pixel_83', '

In [25]:
pd.read_csv(path_to)

serial  pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  \
0           0       70       80       82       72       58       58       60   
1           1      151      150      147      155      148      133      111   
2           2      231      212      156      164      174      138      161   
3           3       24       32       36       30       32       23       19   
4           4        4        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
28704   28704       84       85       85       85       85       85       85   
28705   28705      114      112      113      113      111      111      112   
28706   28706       74       81       87       89       95      100       98   
28707   28707      222      227      203       90       86       90       84   
28708   28708      195      199      205      206      205      203      206   

       pixel_7  pixel_8  ...  pixel_2295  pixel_2296  pixel_2297  pixel_2298  \
0           63       54  ...         182         183         136         106   
1          140      170  ...         108          95         108         102   
2          173      182  ...         138         152         122         114   
3           20       30  ...         126         132         132         133   
4            0        0  ...          34          31          31          31   
...        ...      ...  ...         ...         ...         ...         ...   
28704       85       86  ...          34          35          36          40   
28705      113      115  ...          94         107         120         141   
28706       93      105  ...         214         211         209         200   
28707       77       94  ...         139         141         145         137   
28708      209      208  ...          93          67          34           6   

       pixel_2299  pixel_2300  pixel_2301  pixel_2302  pixel_2303  label_emo  
0             116          95         106         109          82          0  
1              67         171         193         183         184          0  
2             101          97          88         110         152          2  
3             136         139         142         143         142          4  
4              27          31          30          29          30          6  
...           ...         ...         ...         ...         ...        ...  
28704          27         125         231         215         200          2  
28705         144         132         129         182         222          0  
28706         195         192         188         187         187          4  
28707         139         136         136         136         134          0  
28708           7           3           6          15          38          4  

[28709 rows x 2306 columns]

# generate feature map

In [85]:
import numpy as np
import pandas as pd

% matplotlib inline
import torch
from torch import nn
from torch import optim
from torchvision import transforms, models
from torch.autograd import Variable
import torch.utils.data as data
import utils

In [86]:
from fer import FER2013

In [96]:
print('==> Preparing data..')

cut_size = 44

transform_train = transforms.Compose([
    transforms.RandomCrop(44),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
])

transform_train_new = transforms.Compose([
    transforms.RandomCrop(44),
    transforms.ToTensor(),
])

==> Preparing data..


In [88]:
trainset = FER2013(split='Training', transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

PrivateTestset = FER2013(split='PrivateTest', transform=transform_train)
PrivateTestloader = torch.utils.data.DataLoader(PrivateTestset, batch_size=64, shuffle=True)

PublicTestset = FER2013(split='PublicTest', transform=transform_train)
PublicTestloader = torch.utils.data.DataLoader(PublicTestset, batch_size=64, shuffle=True)

In [97]:
trainset = FER2013(split='Training', transform=transform_train_new)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

PrivateTestset = FER2013(split='PrivateTest', transform=transform_train_new)
PrivateTestloader = torch.utils.data.DataLoader(PrivateTestset, batch_size=64, shuffle=True)

PublicTestset = FER2013(split='PublicTest', transform=transform_train_new)
PublicTestloader = torch.utils.data.DataLoader(PublicTestset, batch_size=64, shuffle=True)

In [98]:
# Load ResNet model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = models.resnet50(pretrained=True)

# Remove last softmax layer for deep feature extraction
model = torch.nn.Sequential(*(list(model.children())[:-1]))
model.to(device)

Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)


generate data for training containing private test for memorization

In [99]:
flat_data_arr = []  #input array
target_arr = []  #output array

In [100]:
# Generate deep features from ResNet model by forward pass
def image_feature_loader(dataloader):
    for inputs, labels in dataloader:
        logps = model.forward(inputs.to(device))
        for i in range(len(labels)):
            flat_data_arr.append(np.array(logps[:, :, 0, 0][i].cpu().detach()))
            target_arr.append(np.array(labels[i].cpu().detach()))


image_feature_loader(trainloader)
image_feature_loader(PrivateTestloader)

In [101]:
# Load data into dataframe and save 
flat_data = np.array(flat_data_arr)
target = np.array(target_arr)
df = pd.DataFrame(flat_data)  #dataframe
df['Target'] = target

In [93]:
# Save df to csv
df.to_csv('deepfeature_train_all.csv', index=False)

In [102]:
# Save df to csv
df.to_csv('deepfeature_train_all_withoutflip.csv', index=False)

generate feature for public test

In [ ]:
flat_data_arr_test = []  #input array
target_arr_test = []  #output array

In [ ]:
# Generate deep features from ResNet model by forward pass
def image_feature_loader_test(dataloader):
    for inputs, labels in dataloader:
        logps = model.forward(inputs.to(device))
        print(inputs, labels)
        for i in range(len(labels)):
            flat_data_arr_test.append(np.array(logps[:, :, 0, 0][i].cpu().detach()))
            target_arr_test.append(np.array(labels[i].cpu().detach()))


image_feature_loader_test(PublicTestloader)

In [ ]:
flat_data_test = np.array(flat_data_arr_test)
target_test = np.array(target_arr_test)
df_test = pd.DataFrame(flat_data_test)  #dataframe
df_test['Target'] = target_test

In [ ]:
# Save df to csv
df_test.to_csv('deepfeature_public_test.csv', index=False)

generate feature for private test

In [ ]:
flat_data_arr_pri = []  #input array
target_arr_pri = []  #output array

In [ ]:
# Generate deep features from ResNet model by forward pass
def image_feature_loader_pri(dataloader):
    for inputs, labels in dataloader:
        logps = model.forward(inputs.to(device))
        print(inputs, labels)
        for i in range(len(labels)):
            flat_data_arr_pri.append(np.array(logps[:, :, 0, 0][i].cpu().detach()))
            target_arr_pri.append(np.array(labels[i].cpu().detach()))


image_feature_loader_pri(PrivateTestloader)

In [ ]:
flat_data_pri = np.array(flat_data_arr_pri)
target_pri = np.array(target_arr_pri)
df_pri = pd.DataFrame(flat_data_pri)  #dataframe
df_pri['Target'] = target_pri

In [ ]:
# Save df to csv
df_test.to_csv('deepfeature_private_test.csv', index=False)

run "brainome deepfeature_train_all.csv" to get the result

# training for memorization

In [46]:
batch_size = 64
learning_rate = 0.1
epochs = 250
input_size = 2048
num_classes = 7
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [62]:
class DatasetFromCSV(data.Dataset):
    def __init__(self, csv_path, transform=None):
        self.transform = transform
        self.data = pd.read_csv(csv_path)
        self.labels = np.asarray(self.data.iloc[:, -1])

    def __getitem__(self, index):
        img_feature = np.asarray(self.data.iloc[index][:-1])
        single_img_label = self.labels[index]
        if self.transform is not None:
            img_feature = self.transform(img_feature)
        return (img_feature, single_img_label)

    def __len__(self):
        return len(self.data.index)

In [63]:
transform_train_feature = transforms.Compose([
    transforms.ToTensor(),
])

In [64]:
traindata = DatasetFromCSV('deepfeature_2class.csv', transform=None)
train_loader = torch.utils.data.DataLoader(traindata, batch_size=64, shuffle=True)

print("====End loading training data=====")

====End loading training data=====


In [65]:
class MLP(nn.Module):

    def __init__(self):
        super(MLP, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(input_size, input_size / 2),
            nn.ReLU(inplace=True),
            nn.Linear(input_size / 2, input_size / 4),
            nn.ReLU(inplace=True),
            nn.Linear(200, num_classes),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        x = self.model(x)

        return x

In [66]:
net = MLP()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9, weight_decay=5e-4)

In [84]:
def train():
    global Train_acc
    net.train()
    train_loss = 0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(train_loader):
        inputs, targets = inputs.to(torch.float32), targets.to(torch.float32)
        inputs, targets = inputs.to(device), targets.to(device)

        #         print(type(inputs[0]), type(targets))

        inputs, targets = Variable(inputs), Variable(targets)
        outputs = net(inputs)

        optimizer.zero_grad()
        loss = criterion(outputs, targets.long())
        loss.backward()
        utils.clip_gradient(optimizer, 0.1)
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total += targets.size(0)
        correct += predicted.eq(targets.data).cpu().sum()

        utils.progress_bar(batch_idx, len(train_loader), 'Loss: %.3f | Acc: %.3f%% (%d/%d)'
                           % (train_loss / (batch_idx + 1), 100. * correct / total, correct, total))

    Train_acc = 100. * correct / total
    print("=====train_acc======", Train_acc, "=====epoch=====", epoch)

In [82]:
for epoch in range(epochs):
    train()

 [=============================>] | Loss: 1.719 | Acc: 30.961% (8897/28736)     449/449 449 .........................] | Loss: 1.756 | Acc: 29.818% (229/768)        12/449 13/449  40/449 ....................] | Loss: 1.724 | Acc: 31.818% (1344/4224)      66/449 ] | Loss: 1.724 | Acc: 31.785% (1485/4672)      73/44 86/449 ........] | Loss: 1.724 | Acc: 31.645% (1762/5568)      87/44 90/449 ..] | Loss: 1.716 | Acc: 31.551% (2201/6976)      109/449 ............] | Loss: 1.713 | Acc: 31.436% (3038/9664)      151/449 ................] | Loss: 1.718 | Acc: 31.080% (3481/11200)     175/449 =======>..................] | Loss: 1.718 | Acc: 31.072% (3500/11264)     176/44 178/449 180/449 ======>.................] | Loss: 1.720 | Acc: 31.040% (3695/11904)     186/449 ============>.................] | Loss: 1.720 | Acc: 31.058% (3717/11968)     187/449 ......] | Loss: 1.720 | Acc: 30.909% (4075/13184)     206/449 ....] | Loss: 1.720 | Acc: 30.960% (4161/13440)     210/449 211/44 220/449 240/449 24

 [==================================>] | Loss: 1.720 | Acc: 31.119% (10217/32832)    513/449 
 [==================================>] | Loss: 1.719 | Acc: 31.131% (10241/32896)    514/449 
 [==================================>] | Loss: 1.719 | Acc: 31.132% (10261/32960)    515/449 
 [==================================>] | Loss: 1.719 | Acc: 31.132% (10281/33024)    516/449 
 [==================================>] | Loss: 1.719 | Acc: 31.147% (10306/33088)    517/449 
 [==================================>] | Loss: 1.719 | Acc: 31.178% (10336/33152)    518/449 
 [==================================>] | Loss: 1.719 | Acc: 31.172% (10354/33216)    519/449 
 [==================================>] | Loss: 1.719 | Acc: 31.190% (10380/33280)    520/449 
 [==================================>] | Loss: 1.718 | Acc: 31.214% (10408/33344)    521/449 
 [==================================>] | Loss: 1.718 | Acc: 31.202% (10424/33408)    522/449 
 [==================================>] | Loss: 1.718 | Acc: 

 [=======================================>] | Loss: 1.717 | Acc: 31.145% (11920/38272)    598/449 
 [=======================================>] | Loss: 1.717 | Acc: 31.146% (11940/38336)    599/449 
 [========================================>] | Loss: 1.717 | Acc: 31.133% (11955/38400)    600/449 
 [========================================>] | Loss: 1.717 | Acc: 31.123% (11971/38464)    601/449 
 [========================================>] | Loss: 1.717 | Acc: 31.125% (11992/38528)    602/449 
 [========================================>] | Loss: 1.717 | Acc: 31.102% (12003/38592)    603/449 
 [========================================>] | Loss: 1.717 | Acc: 31.082% (12015/38656)    604/449 
 [========================================>] | Loss: 1.717 | Acc: 31.069% (12030/38720)    605/449 
 [========================================>] | Loss: 1.718 | Acc: 31.064% (12048/38784)    606/449 
 [========================================>] | Loss: 1.718 | Acc: 31.052% (12063/38848)  607/449 
 [==

 [====================================>] | Loss: 1.729 | Acc: 31.766% (11080/34880)    545/449 
 [====================================>] | Loss: 1.730 | Acc: 31.745% (11093/34944)    546/449 
 [====================================>] | Loss: 1.730 | Acc: 31.747% (11114/35008)    547/449 
 [====================================>] | Loss: 1.730 | Acc: 31.752% (11136/35072)    548/449 
 [====================================>] | Loss: 1.730 | Acc: 31.734% (11150/35136)    549/449 
 [====================================>] | Loss: 1.730 | Acc: 31.716% (11164/35200)    550/449 
 [====================================>] | Loss: 1.730 | Acc: 31.712% (11183/35264)    551/449 
 [====================================>] | Loss: 1.730 | Acc: 31.677% (11191/35328)  552/449 
 [====================================>] | Loss: 1.731 | Acc: 31.660% (11205/35392)    553/449 
 [====================================>] | Loss: 1.731 | Acc: 31.650% (11222/35456)    554/449 
 [=====================================>] 

 [=================================>] | Loss: 1.729 | Acc: 31.733% (10256/32320)    505/449 
 [=================================>] | Loss: 1.729 | Acc: 31.716% (10271/32384)    506/449 
 [=================================>] | Loss: 1.729 | Acc: 31.725% (10294/32448)    507/449 
 [=================================>] | Loss: 1.729 | Acc: 31.714% (10311/32512)    508/449 
 [=================================>] | Loss: 1.728 | Acc: 31.717% (10332/32576)    509/449 
 [==================================>] | Loss: 1.729 | Acc: 31.700% (10347/32640)    510/449 
 [==================================>] | Loss: 1.729 | Acc: 31.681% (10361/32704)    511/449 
 [==================================>] | Loss: 1.728 | Acc: 31.683% (10382/32768)    512/449 
 [==================================>] | Loss: 1.728 | Acc: 31.698% (10407/32832)    513/449 
 [==================================>] | Loss: 1.729 | Acc: 31.694% (10426/32896)    514/449 
 [==================================>] | Loss: 1.728 | Acc: 31.70

 [=============================>] | Loss: 1.724 | Acc: 32.005% (9197/28736)     449/449 .....] | Loss: 1.794 | Acc: 33.594% (43/128)         2/449 ............] | Loss: 1.738 | Acc: 32.344% (207/640)        10/449 .........................] | Loss: 1.739 | Acc: 32.528% (229/704)        11/44 12/449 ...................] | Loss: 1.713 | Acc: 34.659% (488/1408)       22/449 ...........] | Loss: 1.715 | Acc: 34.237% (745/2176)       34/449 ..] | Loss: 1.720 | Acc: 33.767% (778/2304)       36/449 ...................] | Loss: 1.718 | Acc: 33.868% (802/2368)       37/449 .........................] | Loss: 1.721 | Acc: 33.799% (822/2432)       38/449  41/449 >..........................] | Loss: 1.730 | Acc: 32.779% (986/3008)       47/449 ..] | Loss: 1.728 | Acc: 32.719% (1047/3200)      50/449 ....] | Loss: 1.723 | Acc: 33.044% (1142/3456)      54/449 55/449 >..........................] | Loss: 1.727 | Acc: 33.147% (1188/3584)      56/449 .....................] | Loss: 1.725 | Acc: 33.432% (1

 [================================>] | Loss: 1.726 | Acc: 31.784% (9764/30720)     480/449 
 [================================>] | Loss: 1.726 | Acc: 31.767% (9779/30784)     481/449 
 [================================>] | Loss: 1.726 | Acc: 31.756% (9796/30848)     482/449 
 [================================>] | Loss: 1.727 | Acc: 31.726% (9807/30912)     483/449 
 [================================>] | Loss: 1.727 | Acc: 31.689% (9816/30976)     484/449 
 [================================>] | Loss: 1.727 | Acc: 31.672% (9831/31040)     485/449 
 [================================>] | Loss: 1.728 | Acc: 31.645% (9843/31104)     486/449 
 [================================>] | Loss: 1.728 | Acc: 31.641% (9862/31168)     487/449 
 [================================>] | Loss: 1.728 | Acc: 31.631% (9879/31232)     488/449 
 [================================>] | Loss: 1.728 | Acc: 31.621% (9896/31296)     489/449 
 [================================>] | Loss: 1.728 | Acc: 31.604% (9911/31360)  

 [=====================================>] | Loss: 1.733 | Acc: 31.280% (11351/36288)    567/449 
 [=====================================>] | Loss: 1.733 | Acc: 31.291% (11375/36352)    568/449 
 [=====================================>] | Loss: 1.733 | Acc: 31.299% (11398/36416)    569/449 
 [======================================>] | Loss: 1.733 | Acc: 31.299% (11418/36480)    570/449 
 [======================================>] | Loss: 1.733 | Acc: 31.307% (11441/36544)    571/449 
 [======================================>] | Loss: 1.733 | Acc: 31.305% (11460/36608)    572/449 
 [======================================>] | Loss: 1.733 | Acc: 31.302% (11479/36672)    573/449 
 [======================================>] | Loss: 1.733 | Acc: 31.291% (11495/36736)    574/449 
 [======================================>] | Loss: 1.733 | Acc: 31.302% (11519/36800)    575/449 
 [======================================>] | Loss: 1.733 | Acc: 31.293% (11536/36864)    576/449 
 [=====================

 [================================>] | Loss: 1.720 | Acc: 32.870% (10203/31040)    485/449 
 [================================>] | Loss: 1.720 | Acc: 32.890% (10230/31104)    486/449 
 [================================>] | Loss: 1.720 | Acc: 32.893% (10252/31168)    487/449 
 [================================>] | Loss: 1.721 | Acc: 32.867% (10265/31232)    488/449 
 [================================>] | Loss: 1.720 | Acc: 32.883% (10291/31296)    489/449 
 [================================>] | Loss: 1.720 | Acc: 32.879% (10311/31360)    490/449 
 [================================>] | Loss: 1.720 | Acc: 32.886% (10334/31424)    491/449 
 [================================>] | Loss: 1.721 | Acc: 32.863% (10348/31488)    492/449 
 [================================>] | Loss: 1.721 | Acc: 32.860% (10368/31552)    493/449 
 [================================>] | Loss: 1.721 | Acc: 32.863% (10390/31616)    494/449 
 [=================================>] | Loss: 1.721 | Acc: 32.854% (10408/31680)

 [======================================>] | Loss: 1.727 | Acc: 32.556% (11918/36608)    572/449 
 [======================================>] | Loss: 1.727 | Acc: 32.545% (11935/36672)    573/449 
 [======================================>] | Loss: 1.727 | Acc: 32.540% (11954/36736)    574/449 
 [======================================>] | Loss: 1.727 | Acc: 32.549% (11978/36800)    575/449 
 [======================================>] | Loss: 1.727 | Acc: 32.560% (12003/36864)    576/449 
 [======================================>] | Loss: 1.727 | Acc: 32.542% (12017/36928)    577/449 
 [======================================>] | Loss: 1.727 | Acc: 32.531% (12034/36992)    578/449 
 [======================================>] | Loss: 1.727 | Acc: 32.526% (12053/37056)    579/449 
 [======================================>] | Loss: 1.727 | Acc: 32.513% (12069/37120)    580/449 
 [======================================>] | Loss: 1.727 | Acc: 32.501% (12085/37184)    581/449 
 [==================

 [================================>] | Loss: 1.758 | Acc: 29.132% (9080/31168)     487/449 
 [================================>] | Loss: 1.758 | Acc: 29.137% (9100/31232)     488/449 
 [================================>] | Loss: 1.758 | Acc: 29.109% (9110/31296)   489/449 
 [================================>] | Loss: 1.759 | Acc: 29.120% (9132/31360)     490/449 
 [================================>] | Loss: 1.758 | Acc: 29.137% (9156/31424)     491/449 
 [================================>] | Loss: 1.758 | Acc: 29.132% (9173/31488)     492/449 
 [================================>] | Loss: 1.758 | Acc: 29.127% (9190/31552)     493/449 
 [================================>] | Loss: 1.759 | Acc: 29.128% (9209/31616)   494/449 
 [=================================>] | Loss: 1.759 | Acc: 29.100% (9219/31680)     495/449 
 [=================================>] | Loss: 1.759 | Acc: 29.086% (9233/31744)     496/449 
 [=================================>] | Loss: 1.759 | Acc: 29.084% (9251/31808)   

 [=============================>] | Loss: 1.734 | Acc: 30.787% (8847/28736)     448/449 /449 >.............................] | Loss: 1.734 | Acc: 29.427% (113/384)        6/449 15/449 =>............................] | Loss: 1.746 | Acc: 29.167% (336/1152)       18/449 ...........................] | Loss: 1.742 | Acc: 29.792% (572/1920)       30/449 31/449 34/449 ..............] | Loss: 1.745 | Acc: 29.464% (660/2240)       35/449 .......................] | Loss: 1.744 | Acc: 29.603% (701/2368)       37/449 .......................] | Loss: 1.744 | Acc: 29.527% (737/2496)       39/449 .................] | Loss: 1.741 | Acc: 29.106% (801/2752)       43/449 45/449 50/449 .....................] | Loss: 1.737 | Acc: 29.369% (1015/3456)      54/449 ....................] | Loss: 1.738 | Acc: 29.325% (1051/3584)      56/449 ===>..........................] | Loss: 1.738 | Acc: 29.386% (1072/3648)      57/449 >..........................] | Loss: 1.738 | Acc: 29.555% (1116/3776)      59/44 60/44 6

 [================================>] | Loss: 1.732 | Acc: 30.946% (9784/31616)     494/449 
 [=================================>] | Loss: 1.732 | Acc: 30.947% (9804/31680)     495/449 
 [=================================>] | Loss: 1.732 | Acc: 30.957% (9827/31744)     496/449 
 [=================================>] | Loss: 1.732 | Acc: 30.964% (9849/31808)   497/449 
 [=================================>] | Loss: 1.732 | Acc: 30.964% (9869/31872)     498/449 
 [=================================>] | Loss: 1.732 | Acc: 30.959% (9887/31936)     499/449 
 [=================================>] | Loss: 1.732 | Acc: 30.972% (9911/32000)     500/449 
 [=================================>] | Loss: 1.732 | Acc: 30.963% (9928/32064)     501/449 
 [=================================>] | Loss: 1.732 | Acc: 30.976% (9952/32128)     502/449 
 [=================================>] | Loss: 1.732 | Acc: 30.989% (9976/32192)     503/449 
 [=================================>] | Loss: 1.732 | Acc: 30.990% (9996/

 [======================================>] | Loss: 1.734 | Acc: 30.833% (11465/37184)    581/449 
 [======================================>] | Loss: 1.734 | Acc: 30.834% (11485/37248)    582/449 
 [======================================>] | Loss: 1.734 | Acc: 30.821% (11500/37312)    583/449 
 [======================================>] | Loss: 1.734 | Acc: 30.819% (11519/37376)    584/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.817% (11538/37440)    585/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.815% (11557/37504)    586/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.811% (11575/37568)    587/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.804% (11592/37632)    588/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.818% (11617/37696)  589/449 
 [=======================================>] | Loss: 1.734 | Acc: 30.842% (11646/37760)    590/449 
 [==============

 [================================>] | Loss: 1.780 | Acc: 27.932% (8813/31552)     493/449 
 [================================>] | Loss: 1.780 | Acc: 27.926% (8829/31616)     494/449 
 [=================================>] | Loss: 1.780 | Acc: 27.939% (8851/31680)     495/449 
 [=================================>] | Loss: 1.780 | Acc: 27.930% (8866/31744)   496/449 
 [=================================>] | Loss: 1.780 | Acc: 27.914% (8879/31808)     497/449 
 [=================================>] | Loss: 1.780 | Acc: 27.909% (8895/31872)     498/449 
 [=================================>] | Loss: 1.780 | Acc: 27.903% (8911/31936)     499/449 
 [=================================>] | Loss: 1.780 | Acc: 27.919% (8934/32000)     500/449 
 [=================================>] | Loss: 1.780 | Acc: 27.925% (8954/32064)     501/449 
 [=================================>] | Loss: 1.780 | Acc: 27.932% (8974/32128)     502/449 
 [=================================>] | Loss: 1.780 | Acc: 27.951% (8998/3

 [======================================>] | Loss: 1.781 | Acc: 27.829% (10330/37120)    580/449 
 [======================================>] | Loss: 1.781 | Acc: 27.810% (10341/37184)    581/449 
 [======================================>] | Loss: 1.781 | Acc: 27.824% (10364/37248)    582/449 
 [======================================>] | Loss: 1.781 | Acc: 27.828% (10383/37312)  583/449 
 [======================================>] | Loss: 1.781 | Acc: 27.831% (10402/37376)    584/449 
 [=======================================>] | Loss: 1.781 | Acc: 27.834% (10421/37440)    585/449 
 [=======================================>] | Loss: 1.781 | Acc: 27.842% (10442/37504)    586/449 
 [=======================================>] | Loss: 1.781 | Acc: 27.853% (10464/37568)    587/449 
 [=======================================>] | Loss: 1.781 | Acc: 27.849% (10480/37632)    588/449 
 [=======================================>] | Loss: 1.781 | Acc: 27.857% (10501/37696)    589/449 
 [===============

KeyboardInterrupt: 

In [83]:
from sklearn.neural_network import MLPClassifier

data = pd.read_csv('deepfeature_2class.csv')
X = data.iloc[:, :-1]
y = data.iloc[:, -1]
clf = MLPClassifier(
    hidden_layer_sizes=(12,), random_state=42,
    activation='relu')
clf.fit(X, y)
(clf.predict(X) == y).sum() / len(y)

E:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:619: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


0.4406025503989659

# train for generalization

In [94]:
use_cuda = torch.cuda.is_available()

In [95]:
traindata = DatasetFromCSV('deepfeature_2class.csv', transform=None)
train_loader = torch.utils.data.DataLoader(traindata, batch_size=64, shuffle=True)

print("====End loading training data=====")

KeyboardInterrupt: 